### ISSUE TITLE
Automatic way to use MDT for all medical modules?

### ISSUE THREAD

**Issue by Mike2023** [coderxio/medication-diversification#89]
# Problem Statement
[What needs to be done and why]
I used Synthea and generated a population of patients without specifying a medical module. That means it uses all medical modules. Per the instructions of MDT, I have to manually replace "MedicationOrder" in every json file of medical module with callsubmodule. Is there an automatic way to do this? Thanks
# Criteria for Success
[Measureable outcome if possible]

# Additional Information
[ways one might accomplish this task, links, documentation, alternatives, etc.]

**Comment by jrlegrand** [comment]
See response here: https://github.com/synthetichealth/synthea/issues/1052
